name: school_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  device_info_plus: ^8.0.0
  dio: ^5.1.0
  dotted_border: ^2.0.0+3
  dots_indicator: ^3.0.0
  email_validator: ^2.1.17
  flutter_svg: ^2.0.0+1
  flutter_cupertino_date_picker_fork: ^1.0.7
  flutter_screenutil: ^5.6.0
  flutter_secure_storage: ^8.0.0
  flutter_otp_text_field: ^1.1.0+2
  get: ^4.6.5
  get_storage: ^2.0.3
  go_router: ^6.0.9
  google_fonts: ^4.0.3
  google_nav_bar: ^5.0.6
  hive_flutter: ^1.1.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.0
  logger: ^1.1.0
  lottie: ^2.2.0
  loading_animation_widget: ^1.2.0+4
  pinput: ^4.0.0
  url_launcher: ^6.1.7
  uuid: ^3.0.7
  video_player: ^2.5.1
  webview_flutter: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/dummy/
    - assets/video/


  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter Bold.ttf
          weight: 700

