import 'package:get/get.dart';

abstract class StringConstants {
  static String appName = 'appName'.tr;
  static String pleaseEnterEmail = 'pleaseEnterEmail'.tr;
  static String password = 'password'.tr;
  static String forgotPassword = 'forgotPassword'.tr;
  static String rememberMe = 'rememberMe'.tr;
  static String signIn = 'signIn'.tr;
  static String home = 'home'.tr;
  static String registerYourSelf = 'registerYourSelf'.tr;
  static String viewAll = 'viewAll'.tr;
  static String viewProfile = 'viewProfile'.tr;
  static String homeWork = 'homeWork'.tr;
  static String academics = 'academics'.tr;
  static String others = 'others'.tr;
  static String noticeBoard = 'noticeBoard'.tr;
  static String timeTable = 'timeTable'.tr;
  static String calender = 'calender'.tr;
  static String forgotPasswordText = 'forgotPasswordText'.tr;
  static String enterMobileNumber = 'enterMobileNumber'.tr;
  static String resetPassword = 'resetPassword'.tr;
  static String checkYouEmail = 'checkYouEmail'.tr;
  static String sendPassword = 'sendPassword'.tr;
  static String pleaseEnterPhoneNumber = 'pleaseEnterPhoneNumber'.tr;
  static String pleaseEnterValidNumber = 'pleaseEnterValidNumber'.tr;
  static String otpVerification = 'OTPVerification'.tr;
  static String pleaseCheckEmail = 'pleaseCheckEmail'.tr;
  static String verificationCode = 'verificationCode'.tr;
  static String resendCode = 'resendCode'.tr;
  static String resend = 'resend'.tr;
  static String otpCode = 'otpCode'.tr;
  static String logoutFromDevice = 'logoutFromDevice'.tr;
  static String submitAssignment = 'submitAssignment'.tr;
  static String events = 'events'.tr;
  static String didNotReceiveCode = 'didNotReceiveCode'.tr;
  static String pleaseEnterValidEmail = 'pleaseEnterValidEmail'.tr;
  static String shouldBe6Characters = 'shouldBe6Characters'.tr;
  static String passwordRequired = 'passwordRequired'.tr;
  static String mobileNumberEmail = 'mobileNumberEmail'.tr;
}
